1. Write a Python Program to find sum of array?


In [18]:
import numpy as np
l1 = []
sum = 0
size = int(input("Enter the size of array"))
for i in range(0,size):
    num = int(input())
    l1.append(num)
array = np.array(l1)
print("array elements are",array)
for j in range(len(array)):
    sum= sum + array[j]
print(sum) 


Enter the size of array4
1
2
3
4
array elements are [1 2 3 4]
10


In [19]:
array.sum()# Function for finding the sum of array elements

10

2. Write a Python Program to find largest element in an array?

In [2]:
import numpy as np
l1 = []
sum = 0
size = int(input("Enter the size of array"))
for i in range(0,size):
    num = int(input())
    l1.append(num)
array = np.array(l1)
print("largest element in array is ",array.max())

Enter the size of array4
12
3
44
5
largest element in array is  44


3. Write a Python Program for array rotation?

In [8]:
array1 = np.array([[1,2,3],[5,6,7]])
print(array1)
rotate_array = np.rot90(array1)
print(rotate_array)

[[1 2 3]
 [5 6 7]]
[[3 7]
 [2 6]
 [1 5]]


4. Write a Python Program to Split the array and add the first part to the end?

In [10]:
def arrray_split(arr,n,split):
    for i in range(0,split):
        x = arr[0]
        for j in range(0,n-1):
            arr[j] = arr[j+1]
        arr[n-1] = x
arr = [1,2,3,4,5,6,7]
n = len(arr)
split = 2
arrray_split(arr,n,split)
print(arr)

[3, 4, 5, 6, 7, 1, 2]


5. Write a Python Program to check if given array is Monotonic?

In [18]:
import numpy as np
def monotonics():
    ar = [1,2,3,4,5]
    arrayy = np.array(ar)
    if np.all(np.diff(arrayy ) > 0):
        print("Monotonic ")
    else:
        print("false")
monotonics()

Monotonic 
