1. Write a Python Program to Add Two Matrices?

In [5]:
import numpy as np
a = np.array([[1,2],[8,9]])
print("Matrix a is \n",a)
b =np.array([[4,5],[3,4]])
print("Matric b is \n",b)
c = a + b
print("Additio is \n",c)

Matrix a is 
 [[1 2]
 [8 9]]
Matric b is 
 [[4 5]
 [3 4]]
Additio is 
 [[ 5  7]
 [11 13]]


2. Write a Python Program to Multiply Two Matrices?

In [7]:
a = np.array([[1,2],[8,9]])
print("Matrix a is \n",a)
b =np.array([[4,5],[3,4]])
print("Matric b is \n",b)
c = a.dot(b)
print("Additio is \n",c)


Matrix a is 
 [[1 2]
 [8 9]]
Matric b is 
 [[4 5]
 [3 4]]
Additio is 
 [[10 13]
 [59 76]]


3. Write a Python Program to Transpose a Matrix?

In [14]:
a = np.array([[1,2],[8,9]])
print("Matrix a is \n",a)
print("Transpose of Matrix is \n",a.T)

Matrix a is 
 [[1 2]
 [8 9]]
Transpose of Matrix is 
 [[1 8]
 [2 9]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [37]:
string = "Hello I am Student Learning DataScience at ineuron"
words = [word.lower() for word in string.split()]
words.sort()
print("The sorted words are")
for i in words:
    print(i)

The sorted words are
am
at
datascience
hello
i
ineuron
learning
student


5. Write a Python Program to Remove Punctuation From a String?

In [41]:
My_string = "Hello there , my name is - Prajwal - Bhongade ?"
punc = '''?!.;'"-,'''
new_string = ""
for i in My_string:
    if i not in punc:
        new_string = new_string + i
print(new_string)

Hello there  my name is  Prajwal  Bhongade 
